format = "$directory$all$localip$kubernetes$cmd_duration$line_break$character"

[character]
success_symbol = "[❯](bold purple)"

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[hostname]
style = "bold yellow"

[memory_usage]
disabled = false

[aws]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[swift]
disabled = true

[ruby]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context(::$namespace)]($style) '

[localip]
disabled = true
ssh_only = false
